name: "!@#$%"
title: "!@#$%"

# baseurl: /expletive/

collections:
  - sections

plugins:
  - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-compress-images

markdown: CommonMark
